shared: &shared
  product_name: 'LLA CRM'
  version: <%= Rails.root.join('VERSION_LLA').read.strip.inspect %>
  compatibility_product: 'Chatwoot'
  compatibility_version: <%= Rails.root.join('VERSION_CW').read.strip.inspect %>

development:
  <<: *shared

production:
  <<: *shared

staging:
  <<: *shared

test:
  <<: *shared
